### ISSUE TITLE
如何插入自己的数据呢？

### ISSUE THREAD

**Issue by baifengbai** [SOVLOOKUP/FastDocx#4]
模板有了，每次生成word要改json文件吗？

**Comment by SOVLOOKUP** [comment]
是的，我的业务场景比较简单，所以目前主要通过Python操作JSON来生成Word，暂时没有交互界面

如果你愿意的话，我会非常支持你来一起参与开发这个功能～

**Comment by baifengbai** [comment]
加载本地的模板和json也是可以的吧，老哥能否加个微信指点下bai7426

**Comment by SOVLOOKUP** [comment]
现在Wordcore.load()方法支持：
1. 加载 http/https 的远程json
2. 加载dict字典类型

本地需要先读取 json 为 dict 再传入
